---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 8800}]
  - name: centos-7.1
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 8801}]
  - name: windows-2012r2
    driver:
      network:
        - ["forwarded_port", {guest: 80, host: 8802}]

suites:
  - name: default
    run_list:
      - recipe[foo::default]
    attributes:
